-- 1a1
SELECT 
COUNT(*)
FROM
PRODUCT_INFORMATION
WHERE
PRODUCT_DESCRIPTION LIKE '%Supra%';


-- 1a2
SELECT
SUBSTR(PRODUCT_DESCRIPTION, INSTR(PRODUCT_DESCRIPTION, 'Supra'),6) AS Drives,
COUNT(*)
FROM PRODUCT_INFORMATION WHERE
PRODUCT_DESCRIPTION LIKE '%Supra%' 
GROUP BY SUBSTR(PRODUCT_DESCRIPTION, INSTR(PRODUCT_DESCRIPTION, 'Supra'),6)
ORDER BY Drives DESC
FETCH FIRST ROW ONLY;


--1b
SELECT 
TRIM('@' FROM REPLACE(substr(CUST_EMAIL, instr(CUST_EMAIL,'@')),'.EXAMPLE.COM',''))AS Suppliers,
COUNT(*) AS Occurrences
FROM CUSTOMERS 
GROUP BY TRIM('@' FROM REPLACE(substr(CUST_EMAIL, instr(CUST_EMAIL,'@')),'.EXAMPLE.COM',''))
ORDER BY 2 DESC
FETCH FIRST ROW ONLY;


--1c
SELECT DISTINCT
INCOME_LEVEL,
LPAD (INCOME_LEVEL,1) AS Category,
(CASE
    WHEN INCOME_LEVEL LIKE '%-%' THEN TRIM(SUBSTR(REPLACE(SUBSTR(INCOME_LEVEL,1, INSTR(INCOME_LEVEL,'-')),' -'),-7))
    WHEN INCOME_LEVEL LIKE '%and above%' THEN TRIM(SUBSTR(INCOME_LEVEL,3,8))
    ELSE Null
END) AS MIN_LEVEL,
(CASE
    WHEN INCOME_LEVEL LIKE '%-%' THEN REPLACE(SUBSTR(INCOME_LEVEL,INSTR(INCOME_LEVEL,'-')),'- ')
    WHEN INCOME_LEVEL LIKE '%Below%' THEN TRIM(SUBSTR(INCOME_LEVEL,-7))
    ELSE Null
END) AS MAX_LEVEL
FROM
CUSTOMERS
ORDER BY 1;