SELECT
SUM("Liczba wszystkich zamówieñ") AS "Ca³kowita liczba wybranych zamówien",
SUM("Wartoœæ wszystkich zamówieñ") AS "Ca³kowita wartoœæ wybranych zamówieñ",
SUM("Wartoœæ rezerwy") AS "Ca³kowita kwota rezerw"

FROM 
(
SELECT
COUNT(oi.PRODUCT_ID) AS "Liczba wszystkich zamówieñ",
SUM(o.ORDER_TOTAL) AS "Wartoœæ wszystkich zamówieñ",
ROUND(SUM(o.ORDER_TOTAL)*0.055,2) AS "Wartoœæ rezerwy"
FROM ORDER_ITEMS oi
JOIN PRODUCT_INFORMATION pi ON pi.PRODUCT_ID = oi.PRODUCT_ID
JOIN ORDERS o ON o.ORDER_ID = oi.ORDER_ID
WHERE o.ORDER_STATUS in (2,3,4,5) AND pi.PRODUCT_NAME LIKE 'HD%' AND ADD_MONTHS(TO_DATE(SUBSTR(o.ORDER_DATE,1,8),'YY/MM/DD'),SUBSTR(pi.WARRANTY_PERIOD,2,2)*12 + SUBSTR(pi.WARRANTY_PERIOD,5,6))>= '30/09/2019'

UNION

SELECT
COUNT(oi.PRODUCT_ID) AS "Liczba wszystkich zamówieñ",
SUM(o.ORDER_TOTAL) AS "Wartoœæ wszystkich zamówieñ",
ROUND(SUM(o.ORDER_TOTAL)*0.1,2) AS "Wartoœæ rezerwy"
FROM ORDER_ITEMS oi
JOIN PRODUCT_INFORMATION pi ON pi.PRODUCT_ID = oi.PRODUCT_ID
JOIN ORDERS o ON o.ORDER_ID = oi.ORDER_ID
WHERE o.ORDER_STATUS in (2,3,4,5) AND pi.PRODUCT_NAME LIKE 'Laptop%' AND ADD_MONTHS(TO_DATE(SUBSTR(o.ORDER_DATE,1,8),'YY/MM/DD'),SUBSTR(pi.WARRANTY_PERIOD,2,2)*12 + SUBSTR(pi.WARRANTY_PERIOD,5,6))>= '30/09/2019'

UNION

SELECT
COUNT(oi.PRODUCT_ID) AS "Liczba wszystkich zamówieñ",
SUM(o.ORDER_TOTAL) AS "Wartoœæ wszystkich zamówieñ",
ROUND(SUM(o.ORDER_TOTAL)*0.08,2) AS "Wartoœæ rezerwy"
FROM ORDER_ITEMS oi
JOIN PRODUCT_INFORMATION pi ON pi.PRODUCT_ID = oi.PRODUCT_ID
JOIN ORDERS o ON o.ORDER_ID = oi.ORDER_ID
WHERE o.ORDER_STATUS in (2,3,4,5) AND pi.PRODUCT_NAME LIKE '%LCD%' AND ADD_MONTHS(TO_DATE(SUBSTR(o.ORDER_DATE,1,8),'YY/MM/DD'),SUBSTR(pi.WARRANTY_PERIOD,2,2)*12 + SUBSTR(pi.WARRANTY_PERIOD,5,6))>= '30/09/2019'

UNION

SELECT
COUNT(oi.PRODUCT_ID) AS "Liczba wszystkich zamówieñ",
SUM(o.ORDER_TOTAL) AS "Wartoœæ wszystkich zamówieñ",
ROUND(SUM(o.ORDER_TOTAL)*0.06,2) AS "Wartoœæ rezerwy"
FROM ORDER_ITEMS oi
JOIN PRODUCT_INFORMATION pi ON pi.PRODUCT_ID = oi.PRODUCT_ID
JOIN ORDERS o ON o.ORDER_ID = oi.ORDER_ID
WHERE o.ORDER_STATUS in (2,3,4,5) AND pi.PRODUCT_NAME LIKE '%Plasma%' AND ADD_MONTHS(TO_DATE(SUBSTR(o.ORDER_DATE,1,8),'YY/MM/DD'),SUBSTR(pi.WARRANTY_PERIOD,2,2)*12 + SUBSTR(pi.WARRANTY_PERIOD,5,6))>= '30/09/2019'

UNION

SELECT
COUNT(oi.PRODUCT_ID) AS "Liczba wszystkich zamówieñ",
SUM(o.ORDER_TOTAL) AS "Wartoœæ wszystkich zamówieñ",
ROUND(SUM(o.ORDER_TOTAL)*0.05,2) AS "Wartoœæ rezerwy"
FROM ORDER_ITEMS oi
JOIN PRODUCT_INFORMATION pi ON pi.PRODUCT_ID = oi.PRODUCT_ID
JOIN ORDERS o ON o.ORDER_ID = oi.ORDER_ID
WHERE o.ORDER_STATUS in (2,3,4,5) AND pi.CATEGORY_ID = 11 AND pi.PRODUCT_NAME NOT LIKE '%Plasma%' AND pi.PRODUCT_NAME NOT LIKE '%LCD%' AND ADD_MONTHS(TO_DATE(SUBSTR(o.ORDER_DATE,1,8),'YY/MM/DD'),SUBSTR(pi.WARRANTY_PERIOD,2,2)*12 + SUBSTR(pi.WARRANTY_PERIOD,5,6))>= '30/09/2019'

UNION

SELECT
COUNT(oi.PRODUCT_ID) AS "Liczba wszystkich zamówieñ",
SUM(o.ORDER_TOTAL) AS "Wartoœæ wszystkich zamówieñ",
ROUND(SUM(o.ORDER_TOTAL)*0.04,2) AS "Wartoœæ rezerwy"
FROM ORDER_ITEMS oi
JOIN PRODUCT_INFORMATION pi ON pi.PRODUCT_ID = oi.PRODUCT_ID
JOIN ORDERS o ON o.ORDER_ID = oi.ORDER_ID
WHERE o.ORDER_STATUS in (2,3,4,5) AND pi.CATEGORY_ID <> 11 AND pi.PRODUCT_NAME NOT LIKE 'Laptop%' AND pi.PRODUCT_NAME NOT LIKE 'HD%' AND ADD_MONTHS(TO_DATE(SUBSTR(o.ORDER_DATE,1,8),'YY/MM/DD'),SUBSTR(pi.WARRANTY_PERIOD,2,2)*12 + SUBSTR(pi.WARRANTY_PERIOD,5,6))>= '30/09/2019')
;