SELECT * FROM
(SELECT
DENSE_RANK() OVER(ORDER BY CUSTOMER_ID DESC) AS THE_BEST_CLIENT,
CUSTOMER_ID,
TO_NUMBER(ORDER_ID),
trunc(TO_DATE(REPLACE(ORDER_DATE,',000000',''), 'YY/MM/DD HH24:MI:SS'), 'DD') AS DATE_OF_ORDER,
ABS(ROUND(sysdate - TO_DATE(REPLACE(ORDER_DATE,',000000',''), 'YY/MM/DD HH24:MI:SS'),0)-LEAD(ROUND(sysdate - TO_DATE(REPLACE(ORDER_DATE,',000000',''), 'YY/MM/DD HH24:MI:SS'),0), 1) OVER (PARTITION BY CUSTOMER_ID ORDER BY ROUND(sysdate - TO_DATE(REPLACE(ORDER_DATE,',000000',''), 'YY/MM/DD HH24:MI:SS'),0))) AS DAYS_BETWEEN_ORDERS
FROM
ORDERS
ORDER BY ORDER_ID DESC)x
WHERE x.THE_BEST_CLIENT = 1;