-- 4a
SELECT PROMO_NAME AS "Nazwa promocji",
(SELECT TO_DATE(SUBSTR(o.ORDER_DATE,1,8),'YY/MM/DD') FROM ORDERS o JOIN PROMOTIONS p ON p.PROMO_ID = o.PROMOTION_ID
    WHERE PROMOTION_ID = 1 ORDER BY ORDER_ID ASC FETCH FIRST ROW ONLY) AS "Data pierwszego zamówienia",
(SELECT TO_DATE(SUBSTR(o.ORDER_DATE,1,8),'YY/MM/DD') FROM ORDERS o JOIN PROMOTIONS p ON p.PROMO_ID = o.PROMOTION_ID
    WHERE PROMOTION_ID = 1 ORDER BY ORDER_ID DESC FETCH FIRST ROW ONLY) AS "Data ostatniego zamówienia"
FROM PROMOTIONS WHERE PROMO_ID = 1
UNION
SELECT PROMO_NAME AS "Nazwa promocji",
(SELECT TO_DATE(SUBSTR(o.ORDER_DATE,1,8),'YY/MM/DD') FROM ORDERS o JOIN PROMOTIONS p ON p.PROMO_ID = o.PROMOTION_ID
    WHERE PROMOTION_ID = 2 ORDER BY ORDER_ID ASC FETCH FIRST ROW ONLY) AS "Data pierwszego zamówienia",
(SELECT TO_DATE(SUBSTR(o.ORDER_DATE,1,8),'YY/MM/DD') FROM ORDERS o JOIN PROMOTIONS p ON p.PROMO_ID = o.PROMOTION_ID
    WHERE PROMOTION_ID = 2 ORDER BY ORDER_ID DESC FETCH FIRST ROW ONLY) AS "Data ostatniego zamówienia"
FROM PROMOTIONS WHERE PROMO_ID = 2;


-- 4b
SELECT 
p.PROMO_NAME AS "Nazwa promocji",
TO_DATE(SUBSTR(o.ORDER_DATE,1,8),'YY/MM/DD') AS "Data zamówienia",
COUNT(o.ORDER_ID)AS "Liczba transakcji w danym dniu",
SUM(o.ORDER_TOTAL) AS "Wartoœæ zamówieñ z calego dnia"
FROM ORDERS o 
JOIN PROMOTIONS p ON p.PROMO_ID = o.PROMOTION_ID
JOIN CUSTOMERS c ON c.customer_id = o.customer_id
WHERE PROMOTION_ID = 1 
GROUP BY (p.PROMO_NAME, TO_DATE(SUBSTR(o.ORDER_DATE,1,8),'YY/MM/DD'))
ORDER BY TO_DATE(SUBSTR(o.ORDER_DATE,1,8),'YY/MM/DD');


-- 4c
(SELECT 
p.PROMO_NAME AS "Nazwa promocji",
o.CUSTOMER_ID AS "ID klienta",
c.CUST_FIRST_NAME AS "Imiê",
c.CUST_LAST_NAME AS "Nazwisko",
TO_DATE(SUBSTR(o.ORDER_DATE,1,8),'YY/MM/DD') AS "Data pierwszego zamówienia"
FROM ORDERS o 
JOIN PROMOTIONS p ON p.PROMO_ID = o.PROMOTION_ID
JOIN CUSTOMERS c ON c.customer_id = o.customer_id
WHERE PROMOTION_ID = 1 
ORDER BY ORDER_ID ASC 
FETCH FIRST ROW ONLY)
UNION 
(SELECT 
p.PROMO_NAME AS "Nazwa promocji",
o.CUSTOMER_ID AS "ID klienta",
c.CUST_FIRST_NAME AS "Imiê",
c.CUST_LAST_NAME AS "Nazwisko",
TO_DATE(SUBSTR(o.ORDER_DATE,1,8),'YY/MM/DD') AS "Data pierwszego zamówienia"
FROM ORDERS o 
JOIN PROMOTIONS p ON p.PROMO_ID = o.PROMOTION_ID
JOIN CUSTOMERS c ON c.customer_id = o.customer_id
WHERE PROMOTION_ID = 2 
ORDER BY ORDER_ID ASC 
FETCH FIRST ROW ONLY);


-- 4d
SELECT
CASE WHEN o.PROMOTION_ID = 1 THEN 'Everyday low price' WHEN o.PROMOTION_ID = 2 THEN 'Blowout sale' ELSE 'Okres niepromocyjny' END Promocja,
TO_NUMBER(SUBSTR(1+(SELECT o.ORDER_DATE FROM ORDERS o
    WHERE o.PROMOTION_ID IS NULL ORDER BY ORDER_ID DESC FETCH FIRST ROW ONLY)-(SELECT o.ORDER_DATE FROM ORDERS o
    WHERE o.PROMOTION_ID IS NULL ORDER BY ORDER_ID ASC FETCH FIRST ROW ONLY),1,10)) AS "Czas trwania w dniach",
COUNT(o.ORDER_ID)AS "Liczba wszystkich transakcji",
ROUND(COUNT(o.ORDER_ID)/TO_NUMBER(SUBSTR(1+(SELECT o.ORDER_DATE FROM ORDERS o
    WHERE PROMOTION_ID IS NULL ORDER BY ORDER_ID DESC FETCH FIRST ROW ONLY)-(SELECT o.ORDER_DATE FROM ORDERS o 
    WHERE PROMOTION_ID IS NULL ORDER BY ORDER_ID ASC FETCH FIRST ROW ONLY),1,10)),2) AS "Œrednia liczba zamówieñ na dzieñ",
ROUND(SUM(o.ORDER_TOTAL),2) AS "Wartoœæ wszystkich zamówieñ",
ROUND(SUM(o.ORDER_TOTAL)/COUNT(o.ORDER_ID),2) AS "Œrednia wartoœæ zamówienia"
FROM ORDERS o 
JOIN CUSTOMERS c ON c.CUSTOMER_ID = o.CUSTOMER_ID
WHERE PROMOTION_ID IS NULL 
GROUP BY (o.PROMOTION_ID)
UNION
SELECT
CASE WHEN o.PROMOTION_ID = 1 THEN 'Everyday low price' WHEN o.PROMOTION_ID = 2 THEN 'Blowout sale' ELSE 'Okres niepromocyjny' END Promocja,
TO_NUMBER(SUBSTR(1+(SELECT o.ORDER_DATE FROM ORDERS o
    WHERE o.PROMOTION_ID = 1 ORDER BY ORDER_ID DESC FETCH FIRST ROW ONLY)-(SELECT o.ORDER_DATE FROM ORDERS o
    WHERE o.PROMOTION_ID = 1 ORDER BY ORDER_ID ASC FETCH FIRST ROW ONLY),1,10)) AS "Czas trwania w dniach",
COUNT(o.ORDER_ID)AS "Liczba wszystkich transakcji",
ROUND(COUNT(o.ORDER_ID)/TO_NUMBER(SUBSTR(1+(SELECT o.ORDER_DATE FROM ORDERS o
    WHERE PROMOTION_ID = 1 ORDER BY ORDER_ID DESC FETCH FIRST ROW ONLY)-(SELECT o.ORDER_DATE FROM ORDERS o 
    WHERE PROMOTION_ID = 1 ORDER BY ORDER_ID ASC FETCH FIRST ROW ONLY),1,10)),2) AS "Œrednia liczba zamówieñ na dzieñ",
ROUND(SUM(o.ORDER_TOTAL),2) AS "Wartoœæ wszystkich zamówieñ",
ROUND(SUM(o.ORDER_TOTAL)/COUNT(o.ORDER_ID),2) AS "Œrednia wartoœæ zamówienia"
FROM ORDERS o 
JOIN CUSTOMERS c ON c.CUSTOMER_ID = o.CUSTOMER_ID
WHERE PROMOTION_ID = 1 
GROUP BY (o.PROMOTION_ID)
UNION
SELECT
CASE WHEN o.PROMOTION_ID = 1 THEN 'Everyday low price' WHEN o.PROMOTION_ID = 2 THEN 'Blowout sale' ELSE 'Okres niepromocyjny' END Promocja,
TO_NUMBER(SUBSTR(1+(SELECT o.ORDER_DATE FROM ORDERS o
    WHERE o.PROMOTION_ID = 2 ORDER BY ORDER_ID DESC FETCH FIRST ROW ONLY)-(SELECT o.ORDER_DATE FROM ORDERS o
    WHERE o.PROMOTION_ID = 2 ORDER BY ORDER_ID ASC FETCH FIRST ROW ONLY),1,10)) AS "Czas trwania w dniach",
COUNT(o.ORDER_ID)AS "Liczba wszystkich transakcji",
ROUND(COUNT(o.ORDER_ID)/TO_NUMBER(SUBSTR(1+(SELECT o.ORDER_DATE FROM ORDERS o
    WHERE PROMOTION_ID = 2 ORDER BY ORDER_ID DESC FETCH FIRST ROW ONLY)-(SELECT o.ORDER_DATE FROM ORDERS o 
    WHERE PROMOTION_ID = 2 ORDER BY ORDER_ID ASC FETCH FIRST ROW ONLY),1,10)),2) AS "Œrednia liczba zamówieñ na dzieñ",
ROUND(SUM(o.ORDER_TOTAL),2) AS "Wartoœæ wszystkich zamówieñ",
ROUND(SUM(o.ORDER_TOTAL)/COUNT(o.ORDER_ID),2) AS "Œrednia wartoœæ zamówienia"
FROM ORDERS o 
JOIN CUSTOMERS c ON c.CUSTOMER_ID = o.CUSTOMER_ID
WHERE PROMOTION_ID = 2 
GROUP BY (o.PROMOTION_ID);